### ISSUE TITLE
ATLA Application Outages

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/atla-omeka#13]
## Summary
There are production outages that resolve themselves within 5-6 minutes or are resolved by a redeploy happening consistently on Omeka. 

Relevant Threads:
- https://assaydepot.slack.com/archives/C0313NK4SMS/p1715094911527769

**Comment by aprilrieger** [comment]
atla is in a place where we think we fixed it but are gonna check tomorrow on it, we may need to persist some thing sin the fleet infra side, but Rob wanted to wait. I have a reminder setup so we can rem, and reffed this bookstack article: https://bookstack.notch8.cloud/books/atla/page/cluster-issues-seen

**Comment by aprilrieger** [comment]
The main issue was that not every node had a loadbalancer (lb) installed on it. There is a secondary issue that is making the health check fail in aws on each lb and will need to get scheduled eventually and is less time sensitive.
